name: Build
on:
  # 手动运行
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World
        if: contains(github.event.action, 'hello')
        run: |
          echo My name is P3TERX.
          echo Hello World!

      - name: TEST
        if: github.event.action == 'test'
        run: |
          echo test
