name: Build And Release
on:
  # 手动运行
  workflow_dispatch
jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout base repo
        uses: actions/checkout@v3
        
      - name: install golang
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
          check-latest: true
      - name: Checkout mindoc repo
        uses: actions/checkout@v3
        with:
          repository: mindoc-org/mindoc
          path: src
          fetch-depth: 0
      - name: build
        id: mindoc_build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x build_amd64.sh
          bash build_amd64.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v2.1
          body_path: README.md
          token: ${{ secrets.GITHUB_TOKEN }}
          target_commitish: main
          draft: false
          files: |
            src/*.zip
