name: Build And Release
on:
  # 手动运行
  workflow_dispatch
jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout base repo
        uses: actions/checkout@v3
        
      - name: install golang
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
          check-latest: true
      - name: Checkout mindoc repo
        uses: actions/checkout@v3
        with:
          repository: mindoc-org/mindoc
          # path: src
          # fetch-depth: 0
      - name: build
        # id: mindoc_build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pwd
          go mod tidy -v
          go build -v -o mindoc_linux_amd64 -ldflags="-linkmode external -extldflags '-static' -w -X 'github.com/mindoc-org/mindoc/conf.VERSION=$TRAVIS_TAG' -X 'github.com/mindoc-org/mindoc/conf.BUILD_TIME=`date`' -X 'github.com/mindoc-org/mindoc/conf.GO_VERSION=`go version`'"
          ./mindoc_linux_amd64 version
          rm -rf cache commands controllers converter .git .github graphics mail models routers utils runtime conf/*.go
          zip -r mindoc_linux_amd64.zip conf static uploads views lib mindoc_linux_amd64 LICENSE.md
          pwd
          ls -all
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v2.1
          body_path: README.md
          token: ${{ secrets.GITHUB_TOKEN }}
          target_commitish: main
          draft: true
          files: |
            *.zip
